version: "2"
services:
    www:
        build: .
        ports: 
            - "8001:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
        depends_on:
            - db
    db:
        image: mysql:5.7.13
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test

# для pgSQL            
    postgres:
        image: postgres:12
        environment:
            POSTGRES_DB: myPgDb
            POSTGRES_USER: pguser
            POSTGRES_PASSWORD: pgtest
        ports:
            - "5432:5432"
        volumes:
            - ./pgdump:/docker-entrypoint-initdb.d
            - pg_persistent:/var/lib/postgresql/data
        networks:
            - default

# pg для волюмс            
volumes:
    persistent:
    pg_persistent:
